ONL-4183 WIP
Ebury/chameleon pull request #413
Opened 2020-09-17 10:44 UTC by jaimeperezpedra

2020-09-17 17:58 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.vue
> -        if (this.isSearchEnabled) {
beautifully this is covered by `@focus="isSearchInputFocus = true"` above

```
afterShow() -> focusSearch() -> this.$refs.searchInput.focus() -> @focus="isSearchInputFocus = true"
```

2020-09-17 17:58 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.vue
> -        if (this.isOpen && this.$refs.searchInput) {
if `isSearchEnabled` then `this.$refs.searchInput` always exists, we should use the former for conditional logic

2020-09-17 17:58 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.vue
> -      if (this.hasCta() && this.isCtaAreaFocus) {
moved below for separation of concerns, here we act on the `nextItem` after we do the `isCtaAreaFocus` blur

2020-09-17 17:58 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.vue
> +      if (this.isSearchEnabled && !this.isSearchInputFocus) {
I think this is more elegant

2020-09-18 07:24 UTC, matallo reviewed
reworded the tests cases, reordered them, and added some more cases

tests seem to pass now, but had to comment out an `update`

2020-09-18 07:24 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.vue
> +        // this.$refs.popover.update();
not super happy about having to comment this

2020-09-18 07:24 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.keyboard-navigation.spec.js
> +import { mount, shallowMount } from '@vue/test-utils';
could we achieve same thing without `shallowMount`? tried many stubs

2020-09-18 14:59 UTC, matallo approved these changes

2020-09-18 16:21 UTC, jmesao approved these changes

2020-09-18 17:06 UTC, mcibique requested changes

2020-09-18 17:28 UTC, mcibique commented
3 bugs to solve:
1. If I open dropdown story and I hit tab multiple times without opening dropdown, I want to see focus jumping from one dropdown to next one.
2. If I tab to a dropdown, open it via space, and there is no CTA nor search, after hitting tab again, it should close it and jump to next dropdown. If there is CTA or search, after opening, first tab should jump to search, next tab to CTA, next tab should close the dropdown and jump to next dropdown
3. If I reload the frame in storybook and I open dropdown "Single value - with CTA/Loading/Search", the search is not focused when the dropdown is open. So if I hit the tab for the first time, it jumps to CTA first, then the next tab jumps to search. It should not behaving like this. It should go to search first, then to CTA.

2020-09-23 17:39 UTC, jaimeperezpedra commented
@mcibique All bugs solved, thx for the help, pls check the last commit ty!

2020-09-24 10:56 UTC, matallo approved these changes
typos, the rest LGTM

2020-09-24 10:56 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.keyboard-navigation.spec.js
> +    it('should lost the focus and close if cta is enabled and is focused', async () => {
typo here and through the document "lose"

2020-09-24 10:56 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.keyboard-navigation.spec.js
> +    it('should lost the focus and close if search is enabled', async () => {
typo

2020-09-24 10:56 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.keyboard-navigation.spec.js
> +    it('should not focus the cta if search and cta are enabled but the cta has nothing to focus', async () => {
line break

2020-09-24 10:56 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.keyboard-navigation.spec.js
> +    it('should not focus the cta if search and cta are enabled but the cta has nothing to focus', async () => {
"if cta is not focusable"

2020-09-24 10:56 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.vue
> +      this.lostFocus();
"loseFocus"

2020-09-24 10:56 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.vue
> +        this.lostFocus();
typo

2020-09-24 10:56 UTC, matallo commented on src/components/ec-dropdown-search/ec-dropdown-search.vue
> +    lostFocus() {
typo

2020-09-24 17:30 UTC, mcibique approved these changes

2020-09-25 07:57 UTC, mgascam approved these changes

2020-09-25 08:02 UTC, merged