feat(ONL-4980): Currency selector placeholder in the Currency Input component
Ebury/chameleon pull request #426
Opened 2020-09-29 12:00 UTC by jafcalvente

Adding the capability of defining a currency selector placeholder in the Currency Input component

2020-09-29 12:04 UTC, matallo requested changes
tests or updated snapshots?

2020-09-29 13:06 UTC, jafcalvente commented
Yep @matallo, I should have created a draft instead of a normal PR. Now I've uploaded all changes, including tests. Thanks.

2020-09-29 13:26 UTC, MaruaEl approved these changes

2020-09-29 14:06 UTC, jmesao approved these changes

2020-09-30 11:02 UTC, matallo approved these changes

2020-09-30 11:21 UTC, merged