ONL-5041 add new icons for fees status
Ebury/chameleon pull request #437
Opened 2020-10-02 15:18 UTC by MaruaEl

- Hello, this Pr will added two new icons, one for the Partially paid status, one for the Returned status. The Partially paid icon needs to have 2 different colors, so we hardcoded the constant one directly in the svg file - as that color will always be gray and only the first part of the icon will change. 
![image](https://user-images.githubusercontent.com/15978652/94939880-a7cbfa80-04ca-11eb-827c-a3abc4137dc9.png)
the second icon is:
![image](https://user-images.githubusercontent.com/15978652/94939926-ba463400-04ca-11eb-8721-911366538afe.png)

2020-10-02 15:19 UTC, MaruaEl commented on src/assets/icons/rounded/partial.svg
> +            <path class="tw-fill-gray-4" d="M8,2.30926389e-14 C11.3922941,0.485229661 14,3.40263923 14,6.92911114 C14,10.4555831 11.3922941,13.3729926 8,13.8582223 L8,2.30926389e-14 Z" id="Right-side
Here we have the hardcoded class

2020-10-02 15:26 UTC, jaimeperezpedra approved these changes

2020-10-05 06:08 UTC, jafcalvente requested changes
You need to update the visual regression snapshots with these two new rounded icons.

2020-10-05 08:18 UTC, mcibique commented
The class tw-fill-gray-4 is always from removed from the final CSS because purgecss cannot find it used anywhere. Purgecss doesn't run on your local but it does run when deploying to now.sh so the class has no effect there.

You have to add SVGs to be scanned into `postcss.config.js`:
```js
config.plugins['@fullhuman/postcss-purgecss'] = {
      content: [
        './src/**/*.vue',
        './src/**/*.story.js',
        './src/**/*.svg',
        './.storybook/*.js'
      ],
```

You can check how is it working/not working by setting 
```
// const isProd = process.env.NODE_ENV === 'production';
const isProd = true;
```
in the same file. You have to restart `npm run start` every time you change that file.

2020-10-05 08:24 UTC, MaruaEl commented
> The class tw-fill-gray-4 is always removed from the final CSS because purgecss cannot find it used anywhere. Purgecss doesn't run on your local but it does run when deploying to now.sh so the class has no effect there.
> 
> You have to add SVGs to be scanned into `postcss.config.js`:
> 
> ```js
> config.plugins['@fullhuman/postcss-purgecss'] = {
>       content: [
>         './src/**/*.vue',
>         './src/**/*.story.js',
>         './src/**/*.svg',
>         './.storybook/*.js'
>       ],
> ```
> 
> You can check how it is working/not working by setting
> 
> ```
> // const isProd = process.env.NODE_ENV === 'production';
> const isProd = true;
> ```
> 
> in the same file. You have to restart `npm run start` every time you change that file.

Good spot!

2020-10-05 10:36 UTC, pelocho approved these changes

2020-10-05 10:37 UTC, MaruaEl commented
> You need to update the visual regression snapshots with these two new rounded icons.

All done Jose - thank you for your review

2020-10-05 11:17 UTC, matallo approved these changes

2020-10-05 11:52 UTC, jafcalvente commented
Hey @MaruaEl, it's true that you already have the chrome snapshots uploaded but we still need also the firefox ones

2020-10-05 14:36 UTC, jmesao approved these changes

2020-10-05 16:37 UTC, MaruaEl commented
> Hey @MaruaEl, it's true that you already have the chrome snapshots uploaded but we still need also the firefox ones

I think now should be it @jafcalvente

2020-10-05 16:57 UTC, merged