WIP component for date range filter ONL-4917
Ebury/chameleon pull request #500
Opened 2020-10-30 12:43 UTC by MaruaEl

WIP Pr to gather feedbacks 
Working on unit tests in the main time

2020-10-30 13:35 UTC, matallo requested changes

2020-10-30 13:35 UTC, matallo commented on src/components/ec-date-range-filter/ec-date-range-filter.vue
> +            placeholder="DD/MM/YYYY"
if we're not supporting yet different locales for our date fields the least we can do is being consistent how we're showing the placeholder (see capitalization) https://bitbucket.org/fxsolutions/eburyonline/src/ba86b02b8b4b249a806b314b41682158588804c5/frontend/src/views/trade-finance/submitted-requests/create-request/components/form/form.vue#lines-265

is the time to start thinking about a date field component? it has commonalities such error messages

2020-10-30 13:35 UTC, matallo commented on src/components/ec-date-range-filter/ec-date-range-filter.vue
> +            @input="errorMessageFromDate = ''"
not sure I find it the best way to do this

2020-10-30 13:35 UTC, matallo commented on src/components/ec-date-range-filter/ec-date-range-filter.vue
> +    value: { // Check we actually need this
do we? AFAIK, we need the separate from and to values, and not something we'll compose for later use, probably we can get rid of this

2020-11-02 17:39 UTC, matallo commented
It's very subtle but the tab reflows when selecting a date and the badge appears, the rest LGTM!

2020-11-02 17:39 UTC, matallo approved these changes

2020-11-03 09:08 UTC, MaruaEl commented
> It's very subtle but the tab reflows when selecting a date and the badge appears, the rest LGTM!

Thank you Carlos for checking it - I think the reflow will be fixed when we develop the badge - because the heigh and width of the badge should be 15px - so a bit smaller than the current one. Maybe I'll add a comment on the badge ticket so we'll be sure that that is done correctly

2020-11-03 09:24 UTC, matallo commented
Fair enough!

2020-11-03 11:04 UTC, stavros-tomas approved these changes

2020-11-03 12:47 UTC, jaimeperezpedra approved these changes

2020-11-03 16:14 UTC, mcibique approved these changes

2020-11-03 16:24 UTC, merged