add blur event in date range filed component
Ebury/chameleon pull request #593
Opened 2020-12-23 11:03 UTC by MaruaEl

This pr will add a blur event on the date range component to let us use validations on blur for ebo

2020-12-23 11:07 UTC, matallo requested changes
Does it come without tests?

2020-12-23 11:09 UTC, MaruaEl commented
> Does it come without tests?

Hi Carlos, I guess I'll have to add one because test coverage is failing. In the beginning thought that maybe it was more an integration test type of thing

2020-12-23 15:37 UTC, matallo approved these changes

2021-01-11 16:44 UTC, jmesao approved these changes

2021-01-12 08:33 UTC, merged